### ISSUE TITLE
 Deprecation Notice?

### ISSUE THREAD

**Issue by bibleuspro** [feedhenry/fh-messaging#79]
https://github.com/feedhenry/fh-messaging#deprecation-notice

I saw the note about deprecation on the master branch, yet I see a fh-v4.5-4.7 branches and those readme's have not deprecation notice. My hope is, deprecation has been canceled? If still planned what other repo's are planned to carry over this functionality? Thanks for addressing this issue. 

Actually I do see that in 4.7 is where the pull request for the dep. happened. So I suppose the question is as above.
"what other repo's are planned to carry over this functionality?" minus Analytics of course (also is that being picked up somewhere else in RHMAP?)
https://github.com/feedhenry/fh-messaging/commit/1096bf4b69e8c3b5d82876498b80fd5d1b74bea8

**Comment by camilamacedo86** [comment]
HI @bibleuspro,

The deprecation notice was added in the release notes of the release 4.6.5, however, it still in discussion internally and was not decided if it will or not removed from the product in the future versions. 

For the next released 4.7 was verified that this feature is working very well for all platforms of client apps with the latest version of fh-mbaas-api and SDKS, however, for the forms application, the metrics cloud request and monthly device are not which indeed is already tracked to be solved in the backlog of this product. 

In the case of the deprecation is set to move forward in the future versions then users will be able to use third-party applications in order to attend this need. For example, google analytics. 

I hope that this information answered your questions. 

c/c @davidffrench
